version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  spring-angular-chat:
    image: simonstick11/spring-angular-chat:latest
    container_name: spring-angular-chat
    ports:
      - "80:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data: